import "./globals.css";
import { Suspense } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import LOADER from './tsx/layout/LOADER';
import SCROLLBAR from './tsx/layout/SCROLLBAR';
import NAVBAR from './tsx/layout/NAVBAR';
import FOOTER from './tsx/layout/FOOTER';
import type { Metadata, Viewport } from "next";
export const metadata: Metadata = {
  title: "Kingfolio",
  description: "Generated by Mücahid Emin Tomakin",
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
};
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  userScalable: true
};
function ScrollbarWithSuspense() {
  return (
    <Suspense fallback={<div id="progressBar" style={{height: '0%'}} />}>
      <SCROLLBAR />
    </Suspense>
  );
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <LOADER />
        <ScrollbarWithSuspense />
        <NAVBAR />
        <main>{children}</main>
        <FOOTER />
        <SpeedInsights />
      </body>
    </html>
  );
}